# Generated by Django 3.1.4 on 2021-01-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scrap',
            new_name='Task',
        ),
    ]
